# Generated by Django 5.0.6 on 2024-05-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_status_alter_reservation_event_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
    ]
